version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Shopify/ruby-dev-exp"
    labels:
      - "dependencies"
      - "ruby"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "prism"
  - package-ecosystem: "npm"
    directory: "vscode/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Shopify/ruby-dev-exp"
    ignore:
      - dependency-name: "@types/vscode"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Shopify/ruby-dev-exp"
    labels:
      - "dependencies"
      - "fixtures"
