name: 'Close stale issues'
on:
  schedule:
    - cron: '30 12 * * *'

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.repository == 'Shopify/ruby-lsp'
    steps:
      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
        with:
          days-before-stale: 60
          days-before-close: 14
          days-before-pr-stale: -1
          days-before-pr-close: -1
          exempt-issue-labels: pinned
          stale-issue-message: This issue is being marked as stale because there was no activity in the last 2 months
